services:
  # Spring Boot App
  - type: web
    name: ecommerce-app
    env: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql:3306/employee_directory
      - key: SPRING_DATASOURCE_USERNAME
        value: springstudent
      - key: SPRING_DATASOURCE_PASSWORD
        value: Asif@1234
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  # MySQL Database (Private Service)
  - type: private_service
    name: mysql
    env: docker
    plan: starter
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    dockerfilePath: ./Dockerfile.mysql
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.internal:3306/employee_directory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: springstudent
      - key: SPRING_DATASOURCE_PASSWORD
        value: Asif@1234
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

