services:
  # Spring Boot App
  - type: web
    name: ecommerce-app
    env: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: >
      bash -lc "for i in {1..30}; do (echo > /dev/tcp/mysql/3306) && break || sleep 2; done; java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.internal:3306/employee_directory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: springstudent
      - key: SPRING_DATASOURCE_PASSWORD
        value: Asif@1234
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    healthCheckPath: /

  # MySQL Database (Private Service) — use official image and standard env vars
  - type: private_service
    name: mysql
    env: docker
    plan: starter
    image: mysql:8.0
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: Asif@1234
      - key: MYSQL_DATABASE
        value: employee_directory
      - key: MYSQL_USER
        value: springstudent
      - key: MYSQL_PASSWORD
        value: Asif@1234

